version: "3.6"
services:
  flask:
    build:
      context: server
      target: server-complete
    volumes:
      - ./datasets:/datasets
    ports:
      - "5000:5000"
    environment:
      DATASETS_DIRECTORY: /datasets
      MONGO_HOST: mongo
      DASK_SCHEDULER_HOST: dask-scheduler:8786


  mongo:
    image: mongo
    restart: always

  dask-scheduler:
    build:
      context: server
      target: server-base
    ports:
      - "8787:8787"

  dask-worker:
    build:
      context: server
      target: server-worker
    volumes:
      - ./datasets:/datasets
    environment:
      PYTHONPATH: /
      MONGO_HOST: mongo
    working_dir: /
    command: ["dask-worker", "dask-scheduler:8786", "--preload", "worker_setup"]

  angular:
    build: front
    ports:
      - 4200:80
