version: "2.4"
services:
  flask:
    build: .
    volumes:
      - ./app:/app
      - ./datasets:/datasets
    environment:
      FLASK_ENV: development
      FLASK_APP: app
      DATASETS_DIRECTORY: /datasets
      MONGO_HOST: mongo
    ports:
      - "5000:5000"
    command: ["flask", "run", "--host=0.0.0.0"]

  mongo:
    image: mongo
    restart: always
