version: "3"
services:
  flask:
    build: server
    volumes:
      - ./server/app:/app
      - ./datasets:/datasets
    environment:
      FLASK_ENV: development
      FLASK_APP: "app:create_app()"
      DATASETS_DIRECTORY: /datasets
      MONGO_HOST: mongo
      DASK_SCHEDULER_HOST: dask-scheduler:8786
    ports:
      - "5000:5000"
    command: ["flask", "run", "--host=0.0.0.0"]

  mongo:
    image: mongo
    restart: always

  dask-scheduler:
    build: server
    ports:
      - "8787:8787"
    command: ["dask-scheduler"]

  dask-worker:
    build: server
    volumes:
      - ./server/app:/app
      - ./datasets:/datasets
    environment:
      PYTHONPATH: /
    working_dir: /
    command: ["dask-worker", "dask-scheduler:8786"]
